// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://iwzrpxekjqpadxhdckjz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3enJweGVranFwYWR4aGRja2p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNjc4MDQsImV4cCI6MjA0ODc0MzgwNH0.UQZ_EesVJzbT5uLC0u5HGm1SnV9HiJwbqOog4AL4KzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);